var rawData = [
    {
      title: 'Project Title',
      type: 'html & css',
      content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis urna in nisl placerat ullamcorper. Sed vehicula fermentum tortor at eleifend. In tellus quam, egestas et libero in, mollis dignissim elit. Nulla a justo tempus, luctus tortor posuere, sodales diam. Sed tristique cursus dolor nec lobortis. Etiam feugiat tincidunt tempus. Nam consequat vel augue non gravida. Cras venenatis orci odio, a pulvinar velit tempor eget. Aenean eget pulvinar justo. Integer mattis aliquam enim, eu blandit justo hendrerit in. Morbi hendrerit id enim auctor congue. Suspendisse maximus tempus mi, a fringilla massa tristique quis. Pellentesque dolor est, molestie id ultricies id, congue vel orci. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec aliquet ex ac pellentesque tempor.'
    },
    {
      title: 'Project Title',
      type: 'Web Design & Front End Development',
      content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis urna in nisl placerat ullamcorper. Sed vehicula fermentum tortor at eleifend. In tellus quam, egestas et libero in, mollis dignissim elit. Nulla a justo tempus, luctus tortor posuere, sodales diam. Sed tristique cursus dolor nec lobortis. Etiam feugiat tincidunt tempus. Nam consequat vel augue non gravida. Cras venenatis orci odio, a pulvinar velit tempor eget. Aenean eget pulvinar justo. Integer mattis aliquam enim, eu blandit justo hendrerit in. Morbi hendrerit id enim auctor congue. Suspendisse maximus tempus mi, a fringilla massa tristique quis. Pellentesque dolor est, molestie id ultricies id, congue vel orci. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec aliquet ex ac pellentesque tempor.'
    },
    {
      title: 'Project Title',
      type: 'Angular.js & MVP',
      content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis urna in nisl placerat ullamcorper. Sed vehicula fermentum tortor at eleifend. In tellus quam, egestas et libero in, mollis dignissim elit. Nulla a justo tempus, luctus tortor posuere, sodales diam. Sed tristique cursus dolor nec lobortis. Etiam feugiat tincidunt tempus. Nam consequat vel augue non gravida. Cras venenatis orci odio, a pulvinar velit tempor eget. Aenean eget pulvinar justo. Integer mattis aliquam enim, eu blandit justo hendrerit in. Morbi hendrerit id enim auctor congue. Suspendisse maximus tempus mi, a fringilla massa tristique quis. Pellentesque dolor est, molestie id ultricies id, congue vel orci. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec aliquet ex ac pellentesque tempor.'
    },{
      title: 'Project Title',
      type: 'node.js & mongoDB',
      content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis urna in nisl placerat ullamcorper. Sed vehicula fermentum tortor at eleifend. In tellus quam, egestas et libero in, mollis dignissim elit. Nulla a justo tempus, luctus tortor posuere, sodales diam. Sed tristique cursus dolor nec lobortis. Etiam feugiat tincidunt tempus. Nam consequat vel augue non gravida. Cras venenatis orci odio, a pulvinar velit tempor eget. Aenean eget pulvinar justo. Integer mattis aliquam enim, eu blandit justo hendrerit in. Morbi hendrerit id enim auctor congue. Suspendisse maximus tempus mi, a fringilla massa tristique quis. Pellentesque dolor est, molestie id ultricies id, congue vel orci. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec aliquet ex ac pellentesque tempor.'
    },{
      title: 'Project Title',
      type: 'graphic design',
      content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis urna in nisl placerat ullamcorper. Sed vehicula fermentum tortor at eleifend. In tellus quam, egestas et libero in, mollis dignissim elit. Nulla a justo tempus, luctus tortor posuere, sodales diam. Sed tristique cursus dolor nec lobortis. Etiam feugiat tincidunt tempus. Nam consequat vel augue non gravida. Cras venenatis orci odio, a pulvinar velit tempor eget. Aenean eget pulvinar justo. Integer mattis aliquam enim, eu blandit justo hendrerit in. Morbi hendrerit id enim auctor congue. Suspendisse maximus tempus mi, a fringilla massa tristique quis. Pellentesque dolor est, molestie id ultricies id, congue vel orci. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec aliquet ex ac pellentesque tempor.'
    },{
      title: 'Project Title',
      type: 'html & Front End Development',
      content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis urna in nisl placerat ullamcorper. Sed vehicula fermentum tortor at eleifend. In tellus quam, egestas et libero in, mollis dignissim elit. Nulla a justo tempus, luctus tortor posuere, sodales diam. Sed tristique cursus dolor nec lobortis. Etiam feugiat tincidunt tempus. Nam consequat vel augue non gravida. Cras venenatis orci odio, a pulvinar velit tempor eget. Aenean eget pulvinar justo. Integer mattis aliquam enim, eu blandit justo hendrerit in. Morbi hendrerit id enim auctor congue. Suspendisse maximus tempus mi, a fringilla massa tristique quis. Pellentesque dolor est, molestie id ultricies id, congue vel orci. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec aliquet ex ac pellentesque tempor.'
    },{
      title: 'Project Title',
      type: 'html & angular.js',
      content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis urna in nisl placerat ullamcorper. Sed vehicula fermentum tortor at eleifend. In tellus quam, egestas et libero in, mollis dignissim elit. Nulla a justo tempus, luctus tortor posuere, sodales diam. Sed tristique cursus dolor nec lobortis. Etiam feugiat tincidunt tempus. Nam consequat vel augue non gravida. Cras venenatis orci odio, a pulvinar velit tempor eget. Aenean eget pulvinar justo. Integer mattis aliquam enim, eu blandit justo hendrerit in. Morbi hendrerit id enim auctor congue. Suspendisse maximus tempus mi, a fringilla massa tristique quis. Pellentesque dolor est, molestie id ultricies id, congue vel orci. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec aliquet ex ac pellentesque tempor.'
    },{
      title: 'Project Title',
      type: 'html & mongoDB',
      content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent facilisis urna in nisl placerat ullamcorper. Sed vehicula fermentum tortor at eleifend. In tellus quam, egestas et libero in, mollis dignissim elit. Nulla a justo tempus, luctus tortor posuere, sodales diam. Sed tristique cursus dolor nec lobortis. Etiam feugiat tincidunt tempus. Nam consequat vel augue non gravida. Cras venenatis orci odio, a pulvinar velit tempor eget. Aenean eget pulvinar justo. Integer mattis aliquam enim, eu blandit justo hendrerit in. Morbi hendrerit id enim auctor congue. Suspendisse maximus tempus mi, a fringilla massa tristique quis. Pellentesque dolor est, molestie id ultricies id, congue vel orci. Nulla facilisi. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec aliquet ex ac pellentesque tempor.'
    },
  ];
